<div class="header-top">
    <div class="custome-header-item inner-container">
        <div class="item-header">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-block-left')->toHtml(); ?>
        </div>
        <div class="item-header right-header">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-block-right')->toHtml(); ?>
        </div>
    </div>
</div>