<div class="menu__column">
        <h4><?php echo __('First Tilte')?></h4>
        <ul>
            <li><a href="#"><?php echo __('Customer Sevice')?></a></li>
            <li><a href="#"><?php echo __('Faq')?></a></li>
            <li><a href="#"><?php echo __('Shipping Information')?></a></li>
            <li><a href="#"><?php echo __('Site terms & Conditions')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('Second Tilte')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('About Us')?>"><?php echo __('About Us')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('Privacy Policy')?></a></li>
            <li><a href="#" id="open-map" title="<?php echo __('Contact Us')?>"><?php echo __('Contact Us')?></a></li>
        </ul>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modalToggle'
        ],
        function(
            $,
            modalToggle
        ) {
            var options = {
                title: 'Contact Us',
                type: 'popup',
                responsive: true,
                contentSelector: '#popup-map',
                toggleEvent: 'click',
                innerScroll: true,
            };
 
            return modalToggle(options, '#open-map');
        }
    );
</script>
<div id="popup-map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1992.5997417996828!2d27.51397443607992!3d53.90672151661629!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sby!4v1553770504758" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>