<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="full-copyright">
    <div class="inner-container">
        <div class="copyrights">
            <div class="copyright">
                <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
            </div>
            <div class="payment-footer">
                <div class="payment">
                    <ul>
                        <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                    </ul>
                </div>
            </div> 
        </div>
    </div>
</div>