<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="full-copyright">
    <div class="inner-container">
        <div class="left-copyrigt">
            <small class="copyright">
                <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
            </small>
        </div>
        <div class="right-copyright">
            Copy Righht
        </div>
    </div>
</div>