
<div class="mge_home-food float-l wid_full">
    <div class="mge-slider float-l">
        <?php
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('slider-home')->toHtml();
        ?>
    </div>
    <div class="mge-images float-l">
        <?php
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('image-home')->toHtml();
        ?>
    </div>
</div>

<div class="mge-wapper float-l wid_full">
    <div class="mge-colums float-l">
        <div class="mge-inner-pd">
            <div class="mge_raw_code mge_content_element mge_raw_html">
                <div class="mge_wrapper">
                    <div class="ads_border_2"></div>
                    <div class="ads_border_1">
                        <div class="mge-box">
                            <span class="pe-7s-back-2">
                                <img src="<?php echo $this->getViewFileUrl('images/icon/share.jpg'); ?>" alt="Demo">
                            </span>
                        </div>
                        <div class="mge-box-text"><h3>Free delivery/oder over $50</h3></div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mge-colums float-l">
        <div class="mge-inner-pd">
            <div class="mge_raw_code mge_content_element mge_raw_html">
                <div class="mge_wrapper">
                    <div class="ads_border_2"></div>
                    <div class="ads_border_1">
                        <div class="mge-box">
                            <span class="pe-7s-back-2">
                                <img src="<?php echo $this->getViewFileUrl('images/icon/heo.jpg'); ?>" alt="Demo">
                            </span>
                        </div>
                        <div class="mge-box-text"><h3>Free delivery/oder over $50</h3></div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mge-colums float-l">
        <div class="mge-inner-pd">
            <div class="mge_raw_code mge_content_element mge_raw_html">
                <div class="mge_wrapper">
                    <div class="ads_border_2"></div>
                    <div class="ads_border_1">
                        <div class="mge-box">
                            <span class="pe-7s-back-2">
                                <img src="<?php echo $this->getViewFileUrl('images/icon/boxgift.jpg'); ?>" alt="Demo">
                            </span>
                        </div>
                        <div class="mge-box-text"><h3>Free delivery/oder over $50</h3></div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="products-home">
    <?php
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('product-home-list')
        ->toHtml();
    ?>
</div>

<div class="tesmimonials-fluid">
    <?php
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('testimonial')
        ->toHtml();
    ?>	
</div>


<script>
    require(["jquery","owlCarousel"],function($,owlCarousel) {
        $(document).ready(function() {
            $('.box-image').owlCarousel({
                loop:true,
                margin:10,
                nav:false,
                dots:true,
                responsive:{
                    0:{
                        items:1
                    },
                    600:{
                        items:1
                    },
                    1000:{
                        items:1
                    }
                }
            })

            // Tesminal
            $('.text-tesmi').owlCarousel({
                loop:true,
                margin:10,
                autoplay:true,
                dots:true,
                dotsContainer:'#dots',
                responsive:{
                    0:{
                        items:1
                    },
                    600:{
                        items:1
                    },
                    1000:{
                        items:1
                    }
                }
            })
        });
    });
</script>