
<div class="mge_home-food float-l wid_full">
    <div class="mge-slider float-l">
        <div class="box-image float-l wid_full">
            <div class="pd-r-15 figure-images">
                <figure class="box-figure">
                    <img src="<?php echo $this->getViewFileUrl('images/img/slider-store.png'); ?>" alt="Demo">
                </figure>
                <div class="box-text">
                    <span class="text-child float-l wid_full">Macatronil</span>
                    <span class="text-child float-l wid_full">with vegetables</span>
                    <div class="box-button float-l"><a>Buy Now</a></div>
                </div>
            </div>

            <div class="pd-r-15 figure-images">
                <figure class="box-figure">
                    <img src="<?php echo $this->getViewFileUrl('images/img/slider-store.png'); ?>" alt="Demo">
                </figure>
                <div class="box-text">
                    <span class="text-child float-l wid_full">Macatronil</span>
                    <span class="text-child float-l wid_full">with vegetables</span>
                    <div class="box-button float-l"><a>Buy Now</a></div>
                </div>
            </div>

            <div class="pd-r-15 figure-images">
                <figure class="box-figure">
                    <img src="<?php echo $this->getViewFileUrl('images/img/slider-store.png'); ?>" alt="Demo">
                </figure>
                <div class="box-text">
                    <span class="text-child float-l wid_full">Macatronil</span>
                    <span class="text-child float-l wid_full">with vegetables</span>
                    <div class="box-button float-l"><a>Buy Now</a></div>
                </div>
            </div>
            
        </div>
    </div>
    <div class="mge-images float-l">
        <div class="pd-l-15">
            <div class="box-image-t float-l wid_full mr-b-15">
                <figure class="box-figure">
                    <img src="<?php echo $this->getViewFileUrl('images/img/banner-product-1.png'); ?>" alt="Demo">
                </figure>
                <div class="text-container text-right text_block_over">
                    <h4>from</h4>
                    <p><span>$19,99</span></p>
                    <h3><a href="#">Yorkshire</a></h3>
                    <p class="category_block">Oat flakes with fig</p>
                </div>
            </div>
            <div class="box-image-b float-l wid_full pd-t-15">
                <figure class="box-figure">
                    <img src="<?php echo $this->getViewFileUrl('images/img/banner-product-2.png'); ?>" alt="Demo">
                </figure>

                <div class="text-container text-left text_block_over text_block_over_2">
                    <h4>from</h4>
                    <p><span>$19,99</span></p>
                    <h3><a href="#">Kalo</a></h3>
                    <p class="category_block">Organic Race Cake</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="mge-wapper float-l wid_full">
    <div class="mge-colums float-l">
        <div class="mge-inner-pd">
            <div class="mge_raw_code mge_content_element mge_raw_html">
                <div class="mge_wrapper">
                    <div class="ads_border_2"></div>
                    <div class="ads_border_1">
                        <div class="mge-box">
                            <span class="pe-7s-back-2">
                                <img src="<?php echo $this->getViewFileUrl('images/icon/share.jpg'); ?>" alt="Demo">
                            </span>
                        </div>
                        <div class="mge-box-text"><h3>Free delivery/oder over $50</h3></div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mge-colums float-l">
        <div class="mge-inner-pd">
            <div class="mge_raw_code mge_content_element mge_raw_html">
                <div class="mge_wrapper">
                    <div class="ads_border_2"></div>
                    <div class="ads_border_1">
                        <div class="mge-box">
                            <span class="pe-7s-back-2">
                                <img src="<?php echo $this->getViewFileUrl('images/icon/heo.jpg'); ?>" alt="Demo">
                            </span>
                        </div>
                        <div class="mge-box-text"><h3>Free delivery/oder over $50</h3></div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mge-colums float-l">
        <div class="mge-inner-pd">
            <div class="mge_raw_code mge_content_element mge_raw_html">
                <div class="mge_wrapper">
                    <div class="ads_border_2"></div>
                    <div class="ads_border_1">
                        <div class="mge-box">
                            <span class="pe-7s-back-2">
                                <img src="<?php echo $this->getViewFileUrl('images/icon/boxgift.jpg'); ?>" alt="Demo">
                            </span>
                        </div>
                        <div class="mge-box-text"><h3>Free delivery/oder over $50</h3></div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="products-home">
    <?php
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('product-home-list')
        ->toHtml();
    ?>
</div>

<div class="home__banner-organic float-l wid_full">
    <div class="banner-images float-l wid_full">
        <img src="<?php echo $this->getViewFileUrl("images/img/banner_meat_03.png"); ?>" alt="Demo">
        <div class="box-text-banner">
            <h2 class="child-text float-l wid_full">Organic Mixed Meat Bundle</h2>
            <h3 class="child-text float-l wid_full">Now available with  only £20 .00</h3>
            <div class="read-more float-l wid_full"><a href="#">Buy Now</a></div>
        </div>
    </div>
</div>

<div class="logo-home float-l wid_full">
    <ul class="my_list">
        <li>
            <img src="<?php echo $this->getViewFileUrl('images/img/brand-77.png'); ?>" alt="Demo">
        </li>
        <li>
            <img src="<?php echo $this->getViewFileUrl('images/img/brand-66.png'); ?>" alt="Demo">
        </li>
        <li>
            <img src="<?php echo $this->getViewFileUrl('images/img/brand-55.png'); ?>" alt="Demo">
        </li>
        <li>
            <img src="<?php echo $this->getViewFileUrl('images/img/brand-44.png'); ?>" alt="Demo">
        </li>
        <li>
            <img src="<?php echo $this->getViewFileUrl('images/img/q2-1240x468.png'); ?>" alt="Demo">
        </li>
        <li>
            <img src="<?php echo $this->getViewFileUrl('images/img/brand-22.png'); ?>" alt="Demo">
        </li>
        <li>
            <img src="<?php echo $this->getViewFileUrl('images/img/brand-11.png'); ?>" alt="Demo">
        </li>
    </ul>
</div>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".my_list").slick({
                loop: true,
                speed: 500,
                slidesToShow: 7,
            });
        });
    });
</script>
