<?php /** @var \Magento\Newsletter\Block\Subscribe $block */?>
            <div class="newsletter-box page-main">
                <div class="pdnewsletter">
                    <div class="title"><strong><?= $block->escapeHtml(__('Signup Newsletter')) ?></strong></div>
                    <div class="content">
                        <form class="form subscribe"
                            novalidate
                            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                            method="post"
                            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                            id="newsletter-validate-detail">
                            <div class="field newsletter">
                                <div class="control">
                                    <input name="email" type="email" id="newsletter"
                                                placeholder="<?= $block->escapeHtmlAttr(__('Enter your email')) ?>"
                                                data-validate="{required:true, 'validate-email':true}"/>
                                </div>
                            </div>
                            <div class="actions">
                                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                                </button>
                            </div>
                        </form>
                    </div>
                    <?= $block->getChildHtml(); ?>
                </div>
            </div>