<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
            <div class="minus"><span title="<?= __('Reduce the quantity'); ?>">-</span></div>
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <div class="plus"><span title="<?= __('Increase the quantity'); ?>">+</span></div>
                <script type="text/javascript">
                    // This is the javascript codes help us to increase and decrease qty
                    require(['jquery'], function($) {
                        $('.box-tocart .minus').on('click', function() {
                            var qty = parseInt($('#qty').val());
                            qty = qty - 1;
                            $('#qty').val(qty).trigger('change');
                        });
                        $('.box-tocart .plus').on('click', function() {
                            var qty = parseInt($('#qty').val());
                            qty = qty + 1;
                            $('#qty').val(qty).trigger('change');
                        });
                        $('#qty').on('change', function() {
                            var qty = parseInt($(this).val());
                            if (qty > 100) {
                                $(this).val('100');
                            } else if (qty < 1) {
                                $(this).val('1');
                            }
                        });
                    });
                </script>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
            
        <div class="product-addto-links" data-role="add-to-links">
            <a href="<?php echo $block->getUrl('wishlist', ['_secure' => true]);?>" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><span><i class="fa fa-heart" aria-hidden="true"></i></span></a>
            
            <?php
                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
            ?>
            <a href="#"
                class="action tocompare"
                title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                role="button">
                <span><i class="fa fa-random" aria-hidden="true"></i></span>
            </a>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
